# How to use: type 'sh train.sh' on your CLI
python train_tapt.py \
--seed 42 \
--model klue/roberta-large \
--train_data /opt/ml/dataset/tapt_data.csv \
--num_labels 30 \
--output_dir ./adaptive \
--save_total_limit 5 \
--save_steps 500 \
--num_train_epochs 3 \
--learning_rate 2e-5 \
--per_device_train_batch_size 32 \
--per_device_eval_batch_size 32 \
--warmup_steps 500 \
--weight_decay 0.01 \
--logging_dir ./logs \
--logging_steps 100 \
--evaluation_strategy epoch \
--eval_steps  500 \
--load_best_model_at_end True \
--save_pretrained ./best_model \
--run_name roberta-large_adaptive_epoch3 \
--tokenize punct \
--n_splits 1 \
--test_size 0.2 \
--project_name new_TAPT \
--entity_name growing_sesame \
--report_to wandb
